"""geojson not unique

Revision ID: 2522cf306c4d
Revises: 54dcad96017e
Create Date: 2025-07-22 22:09:08.691618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2522cf306c4d'
down_revision = '54dcad96017e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint('route_geojson_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_unique_constraint('route_geojson_key', ['geojson'])

    # ### end Alembic commands ###
