"""increase geojson size

Revision ID: 33a824213bbf
Revises: 18cbd7335ed8
Create Date: 2025-07-12 11:57:50.458211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a824213bbf'
down_revision = '18cbd7335ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('geojson',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.String(length=32768),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('geojson',
               existing_type=sa.String(length=32768),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True)

    # ### end Alembic commands ###
